apiVersion: 1

datasources:
  - name: Gestura InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: gestura
      defaultBucket: gestura_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: gestura-influx-admin-token
